### ISSUE TITLE
how to update the website

### ISSUE THREAD

**Issue by manugunkel** [SmartMicroscopy/smartmicroscopy.github.io#1]
Hi @CamachoDejay,
how do I update the website itself after compiling and pushing the jupiter-book back up? Is this automatically done once in a while or do I need to trigger the update somehow?
Cheers,
Manu

**Comment by CamachoDejay** [comment]
Hi Manu,
I think the best explanation is given in this guide: https://jupyterbook.org/en/stable/start/publish.html

In general the steps could be:
1) git clone the repo.
2) Make changes
   2.1 Modification (easier): 
      2.1.1 Choose the page Markdown file e.g. `notes.md`. 
      2.1.2 Modify the content. 
      2.1.3 Build the book [by following this guide](https://jupyterbook.org/en/stable/start/build.html): `jupyter-book build mybookname/`
      2.1.4 Preview the book, you can open the generated HTML files in your browser.
   2.2 New page (a bit more complex) [detailed info in this link](https://jupyterbook.org/en/stable/start/new-file.html)
      2.2.1 Create new Markdown file e.g. `new-page.md` and add content
      2.2.2 Add this file to the index of the book `_toc.yml`. Our TOC is currently very simple but can be more complex, [look at this part of the guide.](https://jupyterbook.org/en/stable/structure/toc.html) 
      2.2.3 follow steps 2.1.3 and 2.1.4
3) Push the build artifact of the website (files in the [_build folder](https://github.com/SmartMicroscopy/smartmicroscopy.github.io/tree/main/_build))
   3.1 Install `gph-import` 
   3.2 From the `main` branch run `ghp-import -n -p -f _build/html`

Let me know if this clarify things
Saludos,
Rafa

**Comment by manugunkel** [comment]
super, thanks Rafa!
